export const USER_ACTION_TYPES = {
    SET_CURRENT_USER: 'user/SET_CURRENT_USER',
    USER_LOADED: 'user/USER_LOADED',
    USER_LOADED_FAILED: 'user/USER_LOADED_FAILED',
    SIGN_IN_SUCCESS: 'user/SIGN_IN_SUCCESS',
    SIGN_IN_FAILED: 'user/SIGN_IN_FAILED',
    REGISTER_SUCCESS: 'user/REGISTER_SUCCESS',
    REGISTER_FAILED: 'user/REGISTER_FAILED',
    SIGN_OUT_SUCCESS: 'user/SIGN_OUT_SUCCESS',
    SIGN_OUT_FAILED: 'user/SIGN_OUT_FAILED',
    CREATE_LINK_TOKEN_SUCCESS: 'user/CREATE_LINK_TOKEN_SUCCESS',
    CREATE_LINK_TOKEN_FAILED: 'user/CREATE_LINK_TOKEN_FAILED',
    PUBLIC_TOKEN_EXCHANGE_SUCCESS: 'user/PUBLIC_TOKEN_EXCHANGE_SUCCESS',
    PUBLIC_TOKEN_EXCHANGE_FAILED: 'user/PUBLIC_TOKEN_EXCHANGE_FAILED'
};
