export const PLAID_ACTION_TYPES = {
    ACCESS_TOKEN_START: 'plaid/ACCESS_TOKEN_START',
    ACCESS_TOKEN_SUCCESS: 'plaid/ACCESS_TOKEN_SUCCESS',
    ACCESS_TOKEN_FAILED: 'plaid/ACCESS_TOKEN_FAILED'
};
